targets:
  - analyte: CO
    terms:
      - coxL
      - cooS
      - carbon monoxide dehydrogenase
  - analyte: cyd_control
    terms:
      - cydA
      - cydB
      - cydX
      - cytochrome bd
  - analyte: NO
    terms:
      - hmp
      - norV
      - norB
      - nitric oxide
      - flavohemoglobin
      - flavorubredoxin
  - analyte: O2
    terms:
      - fnr
      - fixL
      - hemAT
      - oxygen sensor
      - aerotaxis
