cores: 32
printshellcmds: true
rerun-incomplete: true
latency-wait: 60
set-threads:
  detect_anchors_shard: 8
  extract_neighborhoods_shard: 4
set-resources:
  detect_anchors_shard:
    mem_mb: 16000
    runtime: 120
    slurm_partition: compute
  extract_neighborhoods_shard:
    mem_mb: 8000
    runtime: 60
    slurm_partition: compute
